GET http://localhost:3000/orders/6199119d71657d5798176f83

###

GET http://localhost:3000/transactions/JSON/

###

GET http://localhost:3000/orders/JSON/

###

POST http://localhost:3000/
content-type: application/json

{
    "user_id": "user3",
    "stock_symbol": "TRY",
    "order_type": "buy",
    "units": 11,
    "price": 800
}

###

DELETE http://localhost:3000/61994329c1a1178d1306895b

###

PATCH  http://localhost:3000/61994329c1a1178d1306895b
content-type: application/json

{
    "units": 40,
    "price": 1596.38
}

###

POST http://localhost:3000/test
content-type: application/json

{
    "_id": "619913621bb7613d0ecaf65a",
    "units": 44
}

###

