GET http://localhost:3000/orders/6199119d71657d5798176f83

###

GET http://localhost:3000/transactions/JSON/

###

GET http://localhost:3000/orders/JSON/

###

POST http://localhost:3000/
content-type: application/json

{
    "user_id": "user3",
    "stock_symbol": "AMC",
    "order_type": "sell",
    "units": 14,
    "price": 90
}

###

DELETE http://localhost:3000/619913621bb7613d0ecaf65a

###

PATCH  http://localhost:3000/61979e034e3ea144ba311dea
content-type: application/json

{
    "units": 40,
    "price": 1596.38
}

###

POST http://localhost:3000/test
content-type: application/json

{
    "_id": "619913621bb7613d0ecaf65a",
    "units": 44
}

###

